baseURL = 'https://github.com/farkasr215/melbournepredicts.github.io.git/'
languageCode = 'en-us'
title = 'Analysis on the impact of microclimate factors on pedestrian behaviour – or is it the other way around?'
theme = 'contrast-hugo'
publishDir = "docs"
